# Generated by Django 3.0 on 2021-03-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20210302_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matematica', models.CharField(max_length=100)),
                ('Portugues', models.CharField(max_length=100)),
                ('Fisica', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
